version: '3.8'

name: streamly
services:
  verdaccio:
    image: verdaccio/verdaccio:latest
    container_name: verdaccio
    ports:
      - "4873:4873"
    volumes:
      - ./verdaccio/config.yaml:/config/config.yaml
      - ./verdaccio/htpasswd:/verdaccio/conf/htpasswd
      - verdaccio_storage:/verdaccio/storage
      - verdaccio_plugins:/verdaccio/plugins
      - verdaccio_logs:/verdaccio/logs
    restart: unless-stopped

volumes:
  verdaccio_storage:
  verdaccio_plugins:
  verdaccio_logs:
