name: streamly

services:
  gateway-service:
    build: ./apps/server/gateway-service
    ports:
      - 8080:8080
    networks:
      - streamly-network
    environment:
      - NODE_ENV=${NODE_ENV}
      - TZ=${TZ}
      - GATEWAY_PORT=${GATEWAY_PORT}
      - APP_NAME=${APP_NAME}
      - API_PREFIX=${API_PREFIX}
      - APP_DOMAIN=${APP_DOMAIN}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - COOKIE_HTTP_ONLY=${COOKIE_HTTP_ONLY}
      - COOKIE_SECURE=${COOKIE_SECURE}
      - COOKIE_SAME_SITE=${COOKIE_SAME_SITE}
      - COOKIE_MAX_AGE=${COOKIE_MAX_AGE}

networks:
  streamly-network:
